jd:
  ump:
    app-name: <%= systemName %>
    ump-key-prefix: <%=packageName%>.<%=baseName%>.
  jmq:
    app: BalanceService
    user: BalanceService
    password: 2EB21929
    address: jmq-cluster.jd.local:80
    producer:
      retry-times: 3
    consumer:
      longPull: 5000
      pullInterval: 10000
      listeners[0]:
        listener: tradeFinishListener
        topic: tradeFinish
      listeners[1]:
        listener: updateOrderDetailListener
        topic: accountsucc
jdd:
  r2m:
    zk-provider-properties:
      app-name: test-timothy
      zk-connection-str: 172.25.46.201:2181,172.25.46.221:2181,172.25.46.241:2181
    caches:
      - cache-name: demo-cache1
        timeout: 100
      - cache-name: demo-cache2
        timeout: 100
  easyjob:
    server: http://172.25.4.107:80
    appId: splitaccount_clearing_center
    secret: 5f3b2c303a506c46d2228975ec46acd0

rpc:
  server:
    port: 22000
  registry:
    registry: jsf
    address: http://i.jsf.jd.com
  parameters:
    connectTimeout: 90000
  consumers[0]:
    id: consumer-userServiceProvider
    interfaceClazz: com.jdd.jdpay.demo.api.facade.UserServiceProvider
    alias: jsf2.0

spring:
  datasource:
    url: jdbc:mysql://172.25.4.206:3306/spiltaccount?characterEncoding=utf8&useSSL=true&serverTimezone=Hongkong&nullNamePatternMatchesAll=true
    username: m_spiltaccount
    password: hFm0Kk
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filter: contextConsumerFilter

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 10
  mapper-locations: classpath:mapper/*.xml
