info:
  version: 0.0.1

spring:
  application:
    name: <%= systemName %>
  profiles:
    active: ${spring.profiles.active}
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: yizeBXZTY|88417((
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: caffeine
  r2m:                      #spring.r2m为根节点
    enabled: true           #spring.r2m.enabled只有配置该配置并且设置为true才会开启r2m的自动注入，类的实例化名字为 [clusters.id]
    expand: true           #spring.r2m.expand为true时注入扩展的客户端类 R2mExtClient，类的实例化名字为 "ext" +  [clusters.id](首字母大写)
    pool:
      maxWaitMillis: 500
    provider:               #spring.r2m.provider开头的配置用于配置provider
      zkConnectionStr: 172.25.46.201:2181,172.25.46.221:2181,172.25.46.241:2181
      zkTimeout: 25000
    clusters[0]:               #spring.r2m.cluster开头的配置用于配置集群并创建R2M原生客户端
      id: client1
      appName: <%= systemName %>
      maxRedirections: 5
      redisTimeOut: 500

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 10
  mapper-locations: classpath:mapper/*.xml

jdd:
  jmq:
    enabled: true
    apps:
      - transport:
          id: <%= systemName %>_transport
          app: splitaccount
          address: 192.168.166.40:50088
          user: splitaccount
          password: 8B8A5C9D
          epoll: true
        producers:
          - id: splitAccountProducer
            retryTimes: 3
        consumers:
          - id: splitaccount-clearing-center_consumer
            longPull: 5000
            pullInterval: 10000
            listeners:
              - topic: test
                listenerBeanName: userAddListener #消费者的springbean的名称
jsf:
  provider:
    alias: <%= systemName %>
  consumer:
    userServiceProvider:
      alias: <%= systemName %>
      timeout: 5000
    orderIdGenerateFacade:
      alias: cart_jsf_test
      timeout: 5000
